apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: LoadBalancer # use ClusterIP on cloud
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000