apiVersion: consul.hashicorp.com/v1alpha1
# The resource kind is called ProxyDefaults because it configures the defaults for all proxies.
kind: ProxyDefaults
metadata:
  # There can only be one proxy defaults config for the whole Consul installation, and its name must be global.
  name: global
  # You could put it in any namespace, but since it’s configuring the global defaults, it makes sense in the consul namespace.
  namespace: consul
spec:
  config:
    protocol: http
    # configures Envoy’s tracing configuration. Here you’re setting it to emit the traces to the collector named jaeger_collector.
    envoy_tracing_json: | 
      {
        "http":{
          "name":"envoy.tracers.zipkin",
          "typedConfig":{
            "@type":"type.googleapis.com/envoy.config.trace.v3.ZipkinConfig",
            "collector_cluster":"jaeger_collector",
            "collector_endpoint_version":"HTTP_JSON",
            "collector_endpoint":"/api/v2/spans",
            "shared_span_context":false
          }
        }
      }
    #  it’s just configuring the address of the Jaeger collector as jaeger-collector.default:9411
    envoy_extra_static_clusters_json: |
      {
        "connect_timeout":"3.000s",
        "dns_lookup_family":"V4_ONLY",
        "lb_policy":"ROUND_ROBIN",
        "load_assignment":{
          "cluster_name":"jaeger_collector",
          "endpoints":[
            {
              "lb_endpoints":[
                {
                  "endpoint":{
                    "address":{
                      "socket_address":{
                        "address":"jaeger-collector.default",
                        "port_value":9411,
                        "protocol":"TCP"
                      }
                    }
                  }
                }
              ]
            }
          ]
        },
        "name":"jaeger_collector",
        "type":"STRICT_DNS"
      }